id: P004443
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5417
  title: སྨྱུང་བར་གནས་པའི་སྒྲུབ་ཐབས་དང་འབྲེལ་བའི་ཕན་ཡོན་དང་ཉམས་ཁྲིད་ཐེག་པ་མཆོག་གི་སྒོ་འབྱེད་སོགས།
  author: ''
  volumes:
    a882a5905cbb45709a5807ea6fa20c7d:
      image_group_id: I3CN5419
      title: ''
      volume_number: 1
      total_pages: 267
